version: 2.1

orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.5
  docker: circleci/docker@1.5.0

jobs:
  build-and-test:
    parameters:
      node-version:
        type: string
        default: "15.10.0"
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test-ci
      - run:
          name: Copy tests results for storing
          command: |
            mkdir ~/test-results
            cp test-results.xml ~/test-results/
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

  build-docker:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.<< pipeline.number >>
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.<< pipeline.number >>

  deploy-to-heroku:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - heroku/install
      - heroku/check-authentication
      - checkout
      - heroku/push-docker-image:
          app-name: $HEROKU_APP_NAME  
          process-types: web
      - heroku/release-docker-image:
          app-name: $HEROKU_APP_NAME
          process-types: web

workflows:
  node-test-and-deploy:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              node-version: ["13.8", "14.2", "15.11"]
      - build-docker
      - hold-for-approval:
          type: approval
          requires: 
            - build-docker
          filters:
            branches:
              only: master
      - deploy-to-heroku:
          requires: 
            - hold-for-approval
